### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by sbmkrgit** [sanjaysans/Attendance-app#1]
Can You please tell me. 
what to do after linking this app with fire base.
means how to modify cloud firestore and authentication in firebase.

**Comment by sanjaysans** [comment]
You need to enable email & password authentication.
Using the NodeJS script you have to create student, staff, subjects, and enroll students for subjects.
Then you can directly login with the app using the above credentials given while registering in NodeJS server.

**Comment by sbmkrgit** [comment]
I already enabled this email and password authentication.
But can you please help me with this node js script.
I had never worked on node js

**Comment by sanjaysans** [comment]
Just change the admin credential files in nodeJS.
Run "npm install" and then "node app.js"
once the server is up and running use tools like postman to call APIs and add respective data.
